import { AccessDeniedNotice } from "@/components/AccessDeniedNotice";
import { ErpNextError, getCount, listDocs } from "@/lib/erpnext";
import { paginate, parsePage, parsePageSize } from "@/lib/pagination";
import { ListFilterBar, type FilterFieldConfig } from "@/components/ListFilterBar";
import { PaginationControls } from "@/components/PaginationControls";
import { JobCardsTable, type JobCardRow } from "@/components/JobCardsTable";

// Lifecycle filter maps onto `docstatus`, not the raw `status` field — `MFG-JOBCARD-0`'s
// discovery found `status` goes stale after cancel, so filtering by it directly would be
// unreliable for "show me cancelled Job Cards". See `lib/erpStatus.ts`'s `jobCardStatus`.
const LIFECYCLE_OPTIONS = ["Draft", "Submitted", "Cancelled"];
const LIFECYCLE_TO_DOCSTATUS: Record<string, number> = { Draft: 0, Submitted: 1, Cancelled: 2 };

const SORT_OPTIONS = [
  { value: "modified desc", label: "Last updated" },
  { value: "creation desc", label: "Created (newest)" },
  { value: "creation asc", label: "Created (oldest)" },
];

type SearchParams = {
  id?: string;
  work_order?: string;
  operation?: string;
  workstation?: string;
  lifecycle?: string;
  sort?: string;
  page?: string;
  page_size?: string;
};

/**
 * Read-only workspace (`MFG-JOBCARD-1`) — no "+ New" action. Job Cards are auto-generated by
 * ERPNext on Work Order submit (see `docs/backend/05-manufacturing/job-card.md`'s "Creation
 * contract"), never manually created through this app. Row IDs link to the read-only detail
 * page (`[name]/page.tsx`). Cancel/execution actions are separate future packages
 * (`MFG-JOBCARD-LC-1`/`MFG-JOBCARD-2`).
 */
export default async function JobCardsPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  const params = await searchParams;
  const page = parsePage(params.page);
  const pageSize = parsePageSize(params.page_size);
  const startIndex = (page - 1) * pageSize;

  const filters: unknown[] = [];
  if (params.id) filters.push(["name", "like", `%${params.id}%`]);
  if (params.work_order) filters.push(["work_order", "like", `%${params.work_order}%`]);
  if (params.operation) filters.push(["operation", "=", params.operation]);
  if (params.workstation) filters.push(["workstation", "=", params.workstation]);
  if (params.lifecycle && params.lifecycle in LIFECYCLE_TO_DOCSTATUS) {
    filters.push(["docstatus", "=", LIFECYCLE_TO_DOCSTATUS[params.lifecycle]]);
  }

  let jobCards: JobCardRow[];
  let operations: string[] | null;
  let workstations: string[] | null;
  let totalCount: number;
  try {
    [jobCards, operations, workstations, totalCount] = await Promise.all([
      listDocs<JobCardRow>("Job Card", {
        fields: [
          "name",
          "docstatus",
          "status",
          "work_order",
          "operation",
          "workstation",
          "for_quantity",
          "total_completed_qty",
          "expected_start_date",
          "expected_end_date",
        ],
        filters: filters.length > 0 ? filters : undefined,
        limit: pageSize + 1,
        start: startIndex,
        orderBy: params.sort || SORT_OPTIONS[0].value,
      }),
      listDocs<{ name: string }>("Operation", { fields: ["name"], limit: 100 }).then((rows) => rows.map((r) => r.name)),
      listDocs<{ name: string }>("Workstation", { fields: ["name"], limit: 100 }).then((rows) => rows.map((r) => r.name)),
      getCount("Job Card", filters.length > 0 ? filters : undefined),
    ]);
  } catch (e) {
    if (e instanceof ErpNextError && e.status === 403) {
      return (
        <div>
          <h1 className="mb-4 text-2xl font-medium text-graphite-900">Job Cards</h1>
          <AccessDeniedNotice what="Job Cards" />
        </div>
      );
    }
    throw e;
  }

  const { rows: pagedJobCards, hasNextPage } = paginate(jobCards, pageSize);

  const filterFields: FilterFieldConfig[] = [
    { type: "text", name: "id", label: "ID" },
    { type: "text", name: "work_order", label: "Work Order" },
    { type: "select", name: "operation", label: "Operation", options: operations ?? [] },
    { type: "select", name: "workstation", label: "Workstation", options: workstations ?? [] },
    { type: "select", name: "lifecycle", label: "Lifecycle", options: LIFECYCLE_OPTIONS },
  ];

  return (
    <div>
      <div className="mb-4 flex items-center justify-between">
        <h1 className="text-2xl font-medium text-graphite-900">Job Cards</h1>
      </div>

      <ListFilterBar fields={filterFields} sortOptions={SORT_OPTIONS} values={params} />

      <JobCardsTable jobCards={pagedJobCards} startIndex={startIndex} />
      <PaginationControls
        page={page}
        pageSize={pageSize}
        hasNextPage={hasNextPage}
        searchParams={params}
        rowCount={pagedJobCards.length}
        totalCount={totalCount}
      />
    </div>
  );
}
